### ISSUE TITLE
Support for PHP 7.3 and PHP 7.4

### ISSUE THREAD

**Issue by Choinek** [PayU-EMEA/plugin_magento_23#10]
Hello,

I would like to suggest to add php7.3 and php7.4 to composer.json require due to end of life of php 7.2. https://www.php.net/supported-versions.php

Currently we have some environments where we must install Magento with --ignore-platform-reqs due to this module.

Thanks

**Comment by Darkabso** [comment]
Packagist doesn't see version 1.0.4. Is it possible to fix it?

**Comment by regdos** [comment]
Done.
