### ISSUE TITLE
Payu payment orders getting created when navigating to Payu payment page (payu domain)

### ISSUE THREAD

**Issue by ryanfern86goa** [PayU-EMEA/plugin_magento_23#16]
Hi 

We have noticed that the orders are getting created as soon as you click place order on checkout page for payu payment, even before getting redirected to the payu page (payu domain)

If we abandon the checkout by closing the Payu pay page (payu domain) , the order still persist in magento. Are we expecting this to get eventual cancelled based on payu notification to the endpoint created by your module ?

Thanks
Ryan

**Comment by ryanfern86goa** [comment]
Hi @regdos

would appreciate your response for above query.

Thanks

**Comment by regdos** [comment]
Hi @ryanfern86goa 
The time of automatic canceling the order in PayU depends on the selected payment method - https://developers.payu.com/en/overview.html#paymethods
After auto cancel  PayU sends a notification to Shop and plugin changes order status in Magento  https://github.com/PayU-EMEA/plugin_magento_23/blob/master/Controller/Data/NotifyOrderProcessor.php#L65

**Comment by ryanfern86goa** [comment]
Hi @regdos 

Thank you for getting back.

We have noticed a particular scenario where what you mentioned above doesn't work.

Scenario:
1) Add products and go to checkout
2) Select Payu payment -> select visa as an example (not payu cards)
3) click place order ( order is created in magento with "pending" status + email confirmation)
4) redirected to payu domain
5) close the tab or click back or load a different url in the same tab 

Now, in this case magento order is created with Payu authorisation id ( also known as Payu order ID).
No Payu transaction is created because of step 5). This can be confirmed by loggin in Payu portal and noticing no transaction record logged.

Even after 48 hrs the order status is still in "pending" status in magento while the order status in Payu is "cancelled" ( the order status in Payu to "cancel" was told to us by Payu support")

Since the order status in Payu portal is "cancelled" why is it not reflected in Magento ?.

Thanks and look forward to your swift reply ?

Ryan

**Comment by regdos** [comment]
@ryanfern86goa  Please test change https://github.com/PayU-EMEA/plugin_magento_23/commit/c7ee3566fe6a37dcc921f99151fc04131782feb0

**Comment by ryanfern86goa** [comment]
@regdos 

Thank you for this, we will test this and let you know to our earliest.

Thanks again for a quick solution.
