### ISSUE TITLE
Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /app/vendor/magento/module-theme/Controller/Result/JsFooterPlugin.php

### ISSUE THREAD

**Issue by jemoon** [PayU-EMEA/plugin_magento_23#6]
Magento 2.3.3
https://www.dropbox.com/s/7hqj4sxm13u5okv/Screenshot%202020-01-15%2009.26.09.png?dl=0

Prawdopodobna przyczyna to https://www.dropbox.com/s/e72s8bhlbwvlu2z/Screenshot%202020-01-15%2009.28.28.png?dl=0 - ustawienie to w trybie 'production' musi byc wywolane przez 
`bin/magento conf:se dev/js/move_script_to_bottom 1`

**Comment by regdos** [comment]
Udało nam się powtórzyć błąd choć ten błąd nie powoduje przerwania procesowania notyfikacji, tj. zamówienie w M2 zmienia status a w odpowiedzi jest kod HTTP 200 czyli PayU otrzymuje informację, że notyfikacja została poprawnie przetworzona. Ale przyjrzymy się temu błędowi.

**Comment by jemoon** [comment]
@regdos zgadza sie, nie ma z tym problemow i po glebszej analizie uwazam, ze jest to bardziej kwestia po stronie Magento. Gdyby ktos potrzebowal kosmetycznego patcha to mozna uzyc tego https://gist.github.com/jemoon/5de7cf686df9807b443524af470af6ad

**Comment by regdos** [comment]
Magento  11 dni temu zrobiło fix-a w swoich kodach https://github.com/magento/magento2/commit/ff1aa7e5f0a37bf13c9c466c50297843bd949d47#diff-993b4b8a5d22e23aa90eae9d3c96dff2
Jest lepszy od tego powyżej bo nie wykonuje się strpos jeżeli nie content nie jest stringiem
